# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: fecfile_ruby 0.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "fecfile_ruby"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Sai"]
  s.date = "2016-06-11"
  s.description = "An open-source Ruby implementation of FECFile"
  s.email = "core@makeyourlaws.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "fecfile_ruby.gemspec",
    "lib/fecfile_ruby.rb",
    "test/helper.rb",
    "test/test_fecfile_ruby.rb"
  ]
  s.homepage = "http://github.com/makeyourlaws/fecfile_ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "An open-source Ruby implementation of FECFile"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 3.5"])
      s.add_development_dependency(%q<rdoc>, [">= 4.1"])
      s.add_development_dependency(%q<bundler>, [">= 1.7.9"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0.8"])
    else
      s.add_dependency(%q<shoulda>, [">= 3.5"])
      s.add_dependency(%q<rdoc>, [">= 4.1"])
      s.add_dependency(%q<bundler>, [">= 1.7.9"])
      s.add_dependency(%q<jeweler>, [">= 2.0"])
      s.add_dependency(%q<simplecov>, [">= 0.8"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 3.5"])
    s.add_dependency(%q<rdoc>, [">= 4.1"])
    s.add_dependency(%q<bundler>, [">= 1.7.9"])
    s.add_dependency(%q<jeweler>, [">= 2.0"])
    s.add_dependency(%q<simplecov>, [">= 0.8"])
  end
end

